// Mocks generated by Mockito 5.4.5 from annotations
// in dauco/test/presentation/blocs/get_items_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dauco/data/repositories/implementation/import_repository.dart'
    as _i2;
import 'package:dauco/domain/entities/item.entity.dart' as _i5;
import 'package:dauco/domain/usecases/get_items_use_case.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeImportRepository_0 extends _i1.SmartFake
    implements _i2.ImportRepository {
  _FakeImportRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetItemsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetItemsUseCase extends _i1.Mock implements _i3.GetItemsUseCase {
  MockGetItemsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ImportRepository get importRepository =>
      (super.noSuchMethod(
            Invocation.getter(#importRepository),
            returnValue: _FakeImportRepository_0(
              this,
              Invocation.getter(#importRepository),
            ),
          )
          as _i2.ImportRepository);

  @override
  _i4.Future<List<_i5.Item>> execute(dynamic file, int? testId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [file, testId]),
            returnValue: _i4.Future<List<_i5.Item>>.value(<_i5.Item>[]),
          )
          as _i4.Future<List<_i5.Item>>);
}
